### ISSUE TITLE
Please bump Compatible up to: 6.2.3 to 6.3 or the upcoming 6.4

### ISSUE THREAD

**Issue by w3guy** [ActiveCampaign/postmark-wordpress#108]
See title above, to remove the annoying banner shown below

![image](https://github.com/ActiveCampaign/postmark-wordpress/assets/4140659/27b1ac1f-9e16-41f6-9612-f86fef0303f7)

**Comment by pgraham3** [comment]
All set @w3guy. Tested on 6.4 RC4.

<img width="336" alt="Screenshot 2023-11-07 at 8 44 33 AM" src="https://github.com/ActiveCampaign/postmark-wordpress/assets/16660335/cec6c836-7c45-4d1f-b19c-2aabcdacaf1c">
