### ISSUE TITLE
Propagate headers to Postmark API

### ISSUE THREAD

**Issue by atheken** [ActiveCampaign/postmark-wordpress#18]
Currently, only "recognized" headers are assigned to message properties when sending a message. The non-recognized headers are silently ignored by the plugin, but should be passed to the API when sending the message.

**Comment by bompus** [comment]
I'd also like to see this. I'm trying to include headers such as
X-PM-Tag: foo
X-PM-Metadata-foo: bar

But they currently do nothing. Hopefully this can be added soon :)

**Comment by pgraham3** [comment]
Closing this due to age and the plugin does have support for `metadata` and `tags` now via filters.
