### ISSUE TITLE
Allow plugin to be used as a "must-use" plugin

### ISSUE THREAD

**Issue by atheken** [ActiveCampaign/postmark-wordpress#5]
See here for an explanation of the feature: http://gregrickaby.com/create-mu-plugin-for-wordpress/

**Comment by mgibbs189** [comment]
Maybe this is worth its own repo?

The code to convert this into a MU plugin wouldn't be all that different... it'd just involve stripping out the UI and supporting the necessary constants:

```php
define( 'POSTMARK_API_KEY', '' );
define( 'POSTMARK_SENDER_ADDRESS', 'your@email.com' );
define( 'POSTMARK_FORCE_HTML', true );
define( 'POSTMARK_TRACK_OPENS', true );
```
