### ISSUE TITLE
Undefined Constants Warning

### ISSUE THREAD

**Issue by pgraham3** [ActiveCampaign/postmark-wordpress#99]
**PHP Version:** 7.4.30
**WordPress Version:** 5.9.3
**Plugin version:** 1.17.1

**Tools > Site Health** page:

![image](https://user-images.githubusercontent.com/16660335/179297716-4b04a1f1-074b-45ea-af61-c6b7b05cb9de.png)

**Comment by bhubbard** [comment]
@pgraham3 Hmm yeah it's not clear why those would be undefined unless the plugin was modified or running in a non-typical method. We could probably update the debug file to do a check to kill the notice, something like this:

```defined( POSTMARK_DIR ) ? POSTMARK_DIR : 'NOT DEFINED';```

Ideally if not defined we display the text in yellow or red to let them know it's probably an issue.

**Comment by kyletaylored** [comment]
I'm actually getting this as a `Fatal Error` vs just a warning on the Site Info page.

```
Fatal error: Uncaught Error: Undefined constant "POSTMARK_VERSION" in /code/wp-content/plugins/postmark-approved-wordpress-plugin/includes/class-postmark-debug.php:34

Stack trace: 
#0 /code/wp-includes/class-wp-hook.php(307): Postmark_Debug->debug_info(Array) 
#1 /code/wp-includes/plugin.php(191): WP_Hook->apply_filters(Array, Array) 
#2 /code/wp-admin/includes/class-wp-debug-data.php(1461): apply_filters('debug_informati...', Array) 
#3 /code/wp-admin/site-health-info.php(32): WP_Debug_Data::debug_data() 
#4 /code/wp-admin/includes/class-wp-site-health.php(66): require_once('/code/wp-admin/...') 
#5 /code/wp-includes/class-wp-hook.php(307): WP_Site_Health->show_site_health_tab('debug') 
#6 /code/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array) 
#7 /code/wp-includes/plugin.php(476): WP_Hook->do_action(Array) 
#8 /code/wp-admin/site-health.php(205): do_action('site_health_tab...', 'debug') 
#9 {main} thrown in /code/wp-content/plugins/postmark-approved-wordpress-plugin/includes/class-postmark-debug.php on line 34
```

![image](https://user-images.githubusercontent.com/1759794/181310588-e079d0e9-06aa-46f8-aab8-ac9e5e51c801.png)

**PHP Version**: 8.0.21
**WordPress Version**: 6.0.1
**Plugin version**: 1.17.1

**Comment by pgraham3** [comment]
I have a proposed PR for this [here](https://github.com/ActiveCampaign/postmark-wordpress/pull/100). Mind taking a look at that @bhubbard?

I also have it up as a tag (`1.17.2`) on the plugin marketplace.

@kyletaylored can you try out version `1.17.2` and let me know if that resolves the error? 

You can update to version `1.17.2` using the `wp-cli`:

`$ wp plugin update postmark-approved-wordpress-plugin --version=1.17.2`

**Comment by kyletaylored** [comment]
Error still seems to persist.

![image](https://user-images.githubusercontent.com/1759794/181383710-b708a6ed-143c-462d-b3d7-432a2acb836c.png)

```Fatal error: Uncaught Error: Undefined constant "POSTMARK_VERSION" in /code/wp-content/plugins/postmark-approved-wordpress-plugin/includes/class-postmark-debug.php:36 

Stack trace: 
#0 /code/wp-includes/class-wp-hook.php(307): Postmark_Debug->debug_info(Array) 
#1 /code/wp-includes/plugin.php(191): WP_Hook->apply_filters(Array, Array) 
#2 /code/wp-admin/includes/class-wp-debug-data.php(1461): apply_filters('debug_informati...', Array) 
#3 /code/wp-admin/site-health-info.php(32): WP_Debug_Data::debug_data() 
#4 /code/wp-admin/includes/class-wp-site-health.php(66): require_once('/code/wp-admin/...') 
#5 /code/wp-includes/class-wp-hook.php(307): WP_Site_Health->show_site_health_tab('debug') 
#6 /code/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters('', Array) 
#7 /code/wp-includes/plugin.php(476): WP_Hook->do_action(Array) 
#8 /code/wp-admin/site-health.php(205): do_action('site_health_tab...', 'debug') 
#9 {main} thrown in /code/wp-content/plugins/postmark-approved-wordpress-plugin/includes/class-postmark-debug.php on line 36
```

**Comment by pgraham3** [comment]
Thanks @kyletaylored! I see the issue. 

I needed to have the constants' names in quotes for the `defined()` check. I just updated the `1.17.2` tag with that change.

Please reinstall version `1.17.2` and let me know how it goes.

**Comment by kyletaylored** [comment]
Yep, that did it!

![image](https://user-images.githubusercontent.com/1759794/181519685-5afdf49d-fc3f-40a3-ba4f-04a5f16a25ff.png)

**Comment by pgraham3** [comment]
Awesome - thanks for confirming, @kyletaylored! 🫡
